### ISSUE TITLE
Downsampling MeshNeurons and simplifying meshes fails with Blender 4.3

### ISSUE THREAD

**Issue by floesche** [navis-org/navis#174]
**Description**

When using blender 4.3 as a back end, the `downsample_neuron()` function fails with `AttributeError: 'Scene' object has no attribute 'vertices'`.

**To Reproduce**

```python
import navis
n = navis.example_neurons(1, kind="mesh")
n_sm = simplify_mesh_blender(n, F=0.2, inplace=False)
```

**Expected behavior**
`n_sm` should contain the simplified mesh

**Screenshots**

![image](https://github.com/user-attachments/assets/b79a9faf-6200-449b-8407-2d39d5ac012c)

**Your system**
- NAVis version: 1.7 (also briefly tested with 1.9)
- Python version: 3.12.5
- Operating System: Linux

**Comment by schlegelp** [comment]
Fixed with #175
