### ISSUE TITLE
TreeNeuron.prune_at_depth

### ISSUE THREAD

**Issue by clbarnes** [navis-org/navis#35]
Remove all nodes greater than `distance` away from the root, keeping the proximal part. Looks like I could use `geodesic_matrix` to find all nodes further than `distance`, and `remove_nodes` to take all of them out - but I wonder if it might be better to traverse the tree from the root, getting a list of the first such node encountered on each branch, and cutting those. That way we avoid chopping up or rewiring bits of neuron we're going to throw away anyway.

**Comment by schlegelp** [comment]
That should be fairly straight forward! In terms of implementation: I did something similar (albeit on mesh graphs) for `skeletor` and found two approaches to be fast:

1. Using networkx - see [this](https://github.com/schlegelp/skeletor/blob/21812bb9c33c3b5eaffa4580abd4deabe7762cf9/skeletor/skeletonize/utils.py#L12) function
2. igraph's `Graph.shortest_paths`

In its current implementation `navis.geodesic_matrix()` would let you get the distance from a single node to all others nodes but you can't see a limit which makes it inefficient. I might have suggested adding such a limit parameter to `geodesic_matrix()` and then writing a separate function `navis.prune_at_depth` (with a corresponding `TreeNeuron` method). 

I also suspect that `subset_neuron` would be faster than `remove_nodes` but might be worth timing.
 
I'd be happy to have a crack unless you are already on it?

**Comment by schlegelp** [comment]
Actually `geodesic_matrix()` is already surprisingly fast and it uses `scipy.sparse.csgraph.dijkstra` under the hood which accepts a `limit` parameter. So even more straight forward :)

**Comment by clbarnes** [comment]
Great, thank you! I haven't started on it so if it's trivial for you with better understanding of how things fit together already, it'd be much appreciated, but otherwise I'll take a crack tomorrow.

**Comment by schlegelp** [comment]
See 6356b64a6c3a7b8d545a36e1f6cdd96ac7ab9a2e and let me know if that does the trick. 

Minimal example:
```Python
>>> import navis
>>> n = navis.example_neurons(1)
>>> # Reroot to soma
>>> n.reroot(n.soma, inplace=True)
>>> # Prune all twigs farther from the root than 100 microns
>>> # (example neuron are in 8x8x8nm units)
>>> n_pr = navis.prune_at_depth(n,
...                             depth=100e3 / 8,
...                             inplace=False)
```

**Comment by schlegelp** [comment]
Closing this issue for now. Feel free to reopen if `prune_at_depth` needs more attention
