### ISSUE TITLE
Problem importing navis

### ISSUE THREAD

**Issue by AR2202** [navis-org/navis#36]
When using 
`pip install git+git://github.com/schlegelp/navis@master`
followed by 
`import navis`
I get the following error:
AttributeError: type object 'pyoctree.pyoctree.pyoctree.PyOctree' has no attribute '__reduce_cython__'

The following seems to work:
`pip install navis==0.5.1`

This seems to be a new problem, it was still working properly yesterday.
Thanks.

**Comment by schlegelp** [comment]
That's a bit strange. A couple things that would help debugging this:

1. Could you please share the full traceback? 
2. What Python version + operating system are you running?
3. Did you install pyoctree separately (maybe at some point in the past) or was it installed alongside navis?
3. What version of pyoctree is installed: 
```python
import pyoctree
pyoctree.__version__
```

**Comment by AR2202** [comment]
To be honest, I think the problem is on my side. I tried in a new environment and it works fine.

I am using a deepnote notebook.

**Comment by schlegelp** [comment]
OK cool. Let me know if you figure out what the problem was (in case somebody else comes across the same issue).

**Comment by schlegelp** [comment]
Closing this since pyoctree isn't an actual dependency anymore.
