### ISSUE TITLE
plot_flat not an attribute of navis

### ISSUE THREAD

**Issue by dadanhan** [navis-org/navis#61]
Hi, I get the error:

AttributeError: module 'navis' has no attribute 'plot_flat'

when I try to call navis.plot_flat()
Could you help me?

**Comment by schlegelp** [comment]
Hi. My guess would be that you don't have the most up-to-date version. Could you check this:
```python
>>> import navis
>>> print(navis.__version__)
```

**Comment by dadanhan** [comment]
Hi, yep so I was running 0.6.0 and when I upgrade to navis 1.0.0 it works. thank you so much. Sorry for this silly issue.
