### ISSUE TITLE
Meaning of presynaptic and postsynaptic connectors

### ISSUE THREAD

**Issue by dadanhan** [navis-org/navis#63]
Hi,

I am a little confused with the meaning of presynaptic and postsynaptic connectors. Am I correct in thinking that for a CatmaidNeuron, its presynaptic connectors are points where the neuron is sending an output (i.e. the neuron possesses a presynaptic point that sends a signal to another neuron by connecting to a postsynaptic point) and its postsynaptic connectors are points where the neuron is receiving an input from another neuron?

**Comment by clbarnes** [comment]
If this is specific to CatmaidNeurons, it might be a better fit for https://github.com/navis-org/pymaid , but I think the TreeNeuron connector representation might be inspired by CATMAID's anyway, so may be best to leave this here.

In CATMAID representation, the "connector" is a point with no particular sense of direction (conventionally placed somewhere around the T-bar of the synapse). The directionality comes from treenode-connector edges, which have a "relationship" which is either `presynaptic_to` or `postsynaptic_to` (there are other connector relations too but they're much less common): they describe how the treenode relates to the connector node. e.g. the treenode is presynaptic_to the connector node. A treenode which is involved in a treenode-connector edge with the `presynaptic_to` relation is a presynaptic point. These relations are serialised as an integer: presynaptic_to is 0 and postsynaptic_to is 1 according to https://github.com/catmaid/CATMAID/blob/4c7ce2fb420498027adf4f6e31196aea588b9e71/django/applications/catmaid/control/skeletonexport.py#L247

(I sure hope I've got this the right way round...)

**Comment by schlegelp** [comment]
The terminology unfortunately leaves room for confusion - in particular if you haven't worked with CATMAID before. This is complicated by various different (data) structures used to describe connections between neurons employed across datasets. 

As far as I can tell both of you are correct though. If things are still unclear on your end @dadanhan it would be useful if you had some code example to illustrate your question.

**Comment by dadanhan** [comment]
I think it is clear but just to be 100% sure. I explain what I am doing and the code that I have written. 

Let's say I want to figure out, for a neuron of interest, how many 'inputs' (other neurons synapsing onto my neuron of interest) and 'outputs' (my neuron of interest synapsing onto other neurons) it has. I do this in the following way:

'''
Number_of_inputs = neuron_of_interest.n_postsynapses
Number_of_outputs = neuron_of_interest.n_presynapses
'''

Is this correct?

**Comment by clbarnes** [comment]
Yes, in terms of "locations where it receives input" and "locations where it generates output". However, the number of neurons it receives input from is a different question (as most pairs which form relevant connections will have multiple morphological synapses). Then in the insect, which has mainly polyadic synapses, each location where it generates output probably provides input to a handful of partners.

**Comment by dadanhan** [comment]
To find these polyadic synapses, would I cycle through each location for presynaptic and postsynaptic points, compare connector ID with all neurons and find how many other sites have the same connector id? (e.g for a presynaptic site, get the connector ID and cycle through every neuron in the olfactory system for and postsynaptic sites with the same connector ID)

**Comment by schlegelp** [comment]
Just to add that this is now very CATMAID-specific. For example if you were to work with FlyWire, each connector (pre or post) actually represents a single connection.

As for your question re # of in- and outgoing connections: there are multiple ways to get there. 

The quickest way is to just get list of partners:

```python 
>>> import pymaid
>>> # Get the partner table for neuron with ID 16
>>> partners = pymaid.get_partners(16)
>>> n_inputs = partners.loc[partners.relation == 'upstream', '16'].sum()
>>> n_outputs = partners.loc[partners.relation == 'downstream', '16'].sum()
```

The above solution has two caveats:
1. It only shows neurons and CATMAID does not treat single nodes as neurons. 
2. You don't get the location of the synapses. So no easy way to subset to e.g. just the axon or a given neuropil.

Here is slightly more involved solution that works with connectors and will get your everything:

```python
>>> # Grab the neuron
>>> n = pymaid.get_neuron(16)
>>> # For number of inputs, you can just count the number of incoming connectors 
>>> # If a given connectors provides > 1 input to your neuron, it will show up multiple times
>>> n_inputs = n.n_postsynapses
>>> # For the number of outgoing connections we will need to know the number of treenodes 
>>> # "downstream" of connectors:
>>> # First, fetch connector details 
>>> # These include, for each connector, the postsynaptic treenodes (i.e. connections)
>>> cn_details = pymaid.get_connector_details(n.presynapses.connector_id.values)
>>> # Count number of postsynaptic nodes
>>> cn_details['n_postsynaptic_nodes'] = cn_details.postsynaptic_to_node.map(len)
>>> # Extract number of outputs by summing up the number of downstream nodes 
>>> n_outputs = cn_details.n_postsynaptic_nodes.sum()
```

Hope this helps.

**Comment by clbarnes** [comment]
I'd do something like

```python
import pandas as pd
import itertools

# get neurons as my_neurons

conn_dfs = []
for n in my_neurons:
    df = n["connectors"].copy()
    df["skeleton_id"] = [int(n.skeleton_id)] * len(df)
    conn_dfs.append(df)

all_conns = pd.concat(conn_dfs, ignore_index=True)
edges = []

for conn_id in np.unique(conn_dfs["connector_id"]):
    conns = all_conns[all_conns["connector_id"] == conn_id]
    pre_partners = edges[edges["type"] == 0]
    post_partners = edges[edges["type"] != 0]
    for pre_row, post_row in itertools.product(pre_partners.itertuples(), post_partners.itertuples()):
        edges.append((pre_row.skeleton_id, pre_row.node_id, pre_row.connector_id, post_row.node_id, post_row.skeleton_id))

# edges is now a list of tuples of tuple of pre skeleton -> pre treenode -> connector -> post treenode -> post skeleton

```

N.B. untested, some trying remember how pandas works, some guessing how navis stores connectors internally.

There are simpler ways to get this information through the API (and through pymaid as Philipp has shown!), but this might be preferable if you're working with local data.

**Comment by dadanhan** [comment]
Hi guys,
Thank you so much for clarifying this and all the quick replies. I think the original question has been more than answered. I'll close this issue now.
Dan
