### ISSUE TITLE
split_axon_dendrite not generating errors and just quiting

### ISSUE THREAD

**Issue by dadanhan** [navis-org/navis#71]
Hi Philipp,

For some reason, I am having a problem with navis.split_axon_dendrite() because it does not print any error message but it also just does not do anything and the rest of my code after the function stops running. Below is my code:
```python
import navis
import navis.interfaces.neuprint as neu

#connect with neuprint server
client = neu.Client('https://neuprint.janelia.org',dataset='hemibrain:v1.2.1',token=my_api_token)

#get skeletons
alskels = neu.fetch_skeletons(neu.SegmentCriteria(instance='APL_R'))
on = alskels[0]
on = navis.heal_skeleton(on,method='ALL',drop_disc=True).convert_units('um')
print(f'{on.name}')
print(on)
print(f'cablelength (um) = {on.cable_length}')
print(f'N_pre = {on.n_presynapses}')
print(f'N_pos = {on.n_postsynapses}')
print(navis.split_axon_dendrite(on))
split_sections = navis.split_axon_dendrite(on,metric='flow_centrality')

print(split_sections)
axon = split_sections[split_sections.compartment == 'axon'].convert_units('um')
dend = split_sections[split_sections.compartment == 'dendrite'].convert_units('um')
print(axon)
print(dend)
print(axon.cable_length,axon.n_presynapses,axon.n_postsynapses)
print(dend.cable_length,dend.n_presynapses,dend.n_postsynapses)        
```
The output is:
```
APL_R
type            navis.TreeNeuron
name                       APL_R
id                     425790257
n_nodes                   182514
n_connectors              143341
n_branches                 20298
n_leafs                    20835
cable_length        80151.210938
soma                       17368
units             1.0 micrometer
dtype: object
cablelength (um) = 80151.2109375
N_pre = 16190
N_pos = 127151
```
For some reason, it doesn't print any error messages but it also doesn't print what it should be printing after ```print(f'N_pos = {on.n_postsynapses}'```. I have absolutely no idea why this is happening...Could you please help me solve this problem?

**Comment by schlegelp** [comment]
The APL is a monster of a neuron. When I ran this code it effectively stopped at `print(navis.split_axon_dendrite(on))` and started consuming obscene amounts of memory. There must be a bottleneck in the code that simply doesn't scale well. Will have a proper look and let you know. FWIW: smaller neurons should work fine.

**Comment by clbarnes** [comment]
How big is the neuron when serialised? Might be a useful stress test case to keep around.

**Comment by schlegelp** [comment]
This APL is ~12Mb pickled.

I've also found the culprit for the @dadanhan's problem: an inefficient path query in `navis.flow_centrality` (which is called by `split_axon_dendrite`. Should be able to make some improvements on that end soon.

**Comment by clbarnes** [comment]
One day I'll fix my rust implementation of Arbor.js... I've been playing around with some linestring smoothing and simplification stuff too.

**Comment by schlegelp** [comment]
> One day I'll fix my rust implementation of Arbor.js... I've been playing around with some linestring smoothing and simplification stuff too.

Oh cool! Slightly parallel effort with what I started here: https://github.com/navis-org/fastcore

**Comment by schlegelp** [comment]
@dadanhan I pushed a couple changes to the main branch that speed up the flow metrics functions. If you install `navis` from Github your above code should go through albeit still not super fast: `navis.split_axon_dendrite(on, metric='flow_centrality')` takes ~7min on my laptop... I would avoid calling it multiple times.

A note on how `split_axon_dendrite` works: you can play around with the `flow_thresh` parameter to improve the split. If you do that you can avoid having to re-calculate the flow every time you run the function by calculate it beforehand:

```python
>>> # From your above example
>>> on.reroot(on.soma, inplace=True)
>>> navis.flow_centrality(on)
>>> # `on` now has a "flow_centrality" column in the node table (check e.g. `on.nodes.head()`)
>>> # Splitting now re-uses the column 
>>> splits = navis.split_axon_dendrite(on, metric='flow_centrality', flow_thresh=0.9)
```

That way the actual `navis.split_axon_dendrite` call only takes a minutes or so.

Also not sure how well this algorithm works on something like the APL with its many parallel fibres. Here's a screenshot coloured by flow centrality (`navis.plot3d(on, color_by='flow_centrality', palette='viridis')`. As you can see the neurite with the highest centrality runs the entire length of the peduncle + lobes and then circles around. No clue whether that makes sense for this neuron or whether the skeleton has a messed up topology.

<img width="625" alt="Screenshot 2021-12-02 at 15 38 10" src="https://user-images.githubusercontent.com/7161148/144453699-c8a3d4ba-c360-4dec-9678-700a2a7c0027.png">

**Comment by dadanhan** [comment]
Thank you Philipp!
