### ISSUE TITLE
Blender Blobs from Neuromorpho

### ISSUE THREAD

**Issue by psynaptix1** [navis-org/navis#74]
I got navis to fetch neurons from neuromorpho in Blender. After I ran the following code:

```python
import navis
import navis.interfaces.blender as b3d
from navis.interfaces import neuromorpho as nmc

h = b3d.Handler()
nl = nmc.get_neuron('162173')
h.add(nl)
```
I got the following blob.

![neuromorpho_blob](https://user-images.githubusercontent.com/96073205/145909985-51dc1547-d5af-4f40-a1e4-a1eae0fb05be.PNG)

Any suggestions? Example neurons from navis load just fine.

**Comment by schlegelp** [comment]
Best guess is that it's a problem with the scaling: the Blender interface's defaults are made or data in `nm` but these neurons might well be in `microns`. Try the following:

```python
>>> # Use scaling 1/10 instead of the default  1/10_000
>>> h = b3d.Handler(scaling=1/10)
>>> h.add(nl)
```

**Comment by psynaptix1** [comment]
That seemed to work better. Thank you for the help. Follow up question: I'm assuming the size of the neurons scales with the size of the organism? Therefore when exporting data from different databases, one should keep in mind the size of the organism it was recorded from and scale accordingly?

**Comment by schlegelp** [comment]
In principal yes. Hence that `scaling` parameter for the handler.
