### ISSUE TITLE
color skeleton branches by the strahler index in blender

### ISSUE THREAD

**Issue by artxz** [navis-org/navis#76]
Hi Philipp,

we're making some animation in Blender and using the navis API. We'd like to plot a CATMAID neuron and color its dendritic branches by the strahler index. Any suggestions how to go about it ?

**Comment by schlegelp** [comment]
I can look into making this a straight forward thing via `navis` but for now you could just import each Strahler index as a separate neuron:

```python
import navis
import navis.interfaces.blender as b3d

h = b3d.Handler()

# Using an example neuron here - replace with your CATMAID neuron
s = navis.example_neurons(1)
s.reroot(s.soma, inplace=True)

# Get Strahler indices (SI)
navis.strahler_index(s)

# Create a dictionary for quick lookup
si = s.nodes.set_index('node_id').strahler_index.to_dict()

# Iterate over all Strahler indices
for i in s.nodes.strahler_index.unique():
    # Get all segments that start with this SI 
    # (necessary to avoid gaps)
    segs = [seg for seg in s.small_segments if si[seg[0]] == i]
    # Flatten segments to list of nodes
    nodes = [n for seg in segs for n in seg]  
    # Create a subset of the original neuron with just this SI
    this_si = navis.subset_neuron(s, nodes)
    # Use SI as id and add (need to use string because of Blender)
    this_si.id = str(i)    
    h.add(this_si, connectors=False)    
    # Select this fragment
    sel = h.select(this_si.id)
    # Determine alpha value
    a = 1 / s.nodes.strahler_index.max() * i
    # Set color (R, G, B, A)
    sel.color(.9, .9, .9, a)
```

Two additional notes:
1. I just tried out Blender 3.0 for the first time and had to push a small fix for `navis` to make the skeleton import work again. If you're using 3.0 you need to install/update from Github to make it work.
2. I never bothered with Blender's extensive material system and support for colouring stuff via `navis` is rather rudimentary.

**Comment by artxz** [comment]
This works brilliant in Blender 2.82.  Thank you!
