### ISSUE TITLE
Handle symlinked `transformix` executables

### ISSUE THREAD

**Issue by jasper-tms** [navis-org/navis#81]
The `transformix` executable on my path is a symlink to where the file actually lives:

    Jaspers-MacBook-Pro:~/software/executables$ ls -l transformix
    lrwxrwxr-x  1 jasper  staff  36 Jul 27  2021 transformix -> ../elastix-5.0.1-mac/bin/transformix

I seem to be causing myself unnecessary trouble with this setup since this is a corner case that is often not considered, but for now let's say I want to stick with this. The current navis implementation of `find_elastixbin` function get tricked by this setup. You can handle this situation by changing these two lines: https://github.com/navis-org/navis/blob/e87d2676c1612cdcfd03c51c9943825775b51f93/navis/transforms/elastix.py#L41-L42

to instead be

    return next(path.glob(tool)).resolve().parent

I have tested this change and it works on my computer. It looks to me like it would work on more standard setups but I haven't tested it.

(My original implementation of this find-the-elastix-lib-folder algorithm uses slightly different commands but also handles this case of a symlinked executable, see
https://github.com/jasper-tms/pytransformix/blob/9cbca2acb874b3a2bc19af0133aafb2a1841be17/transformix/core.py#L77-L78)

Thanks Philipp!

**Comment by schlegelp** [comment]
Hi Jasper. Thanks for the hint! Implemented with c38ab64a5cc2b7365b386a7141d0d7552223895f for both Elastix and CMTK. Will release a new navis version to PyPI later today.
