### ISSUE TITLE
Excitatory / Inhibitory information about synapses in neuprint

### ISSUE THREAD

**Issue by jakobtroidl** [navis-org/navis#82]
I wondered if there is a way to get an excitatory/inhibitory labeling of synapses through the neuprint interface. I haven't seen information about that labeling yet. Are there any hints on whether the data is available and how I could access it? Thank you.

**Comment by schlegelp** [comment]
I assume you're referring to the Janelia hemibrain dataset? As far as I know the neurotransmitter predictions aren't yet publicly available. 

Under the hood, `navis` uses [`neuprint-python`](https://github.com/connectome-neuprint/neuprint-python) to fetch data and assemble neurons. The function for fetching synapses (`neuprint.fetch_synapses`) has the fields it returns hard-coded and they wouldn't yet include neurotransmitter predictions. That would need to be changed before the predictions become available. @stuarteberg you don't happen to have that sitting in some branch already? I could have a crack if not.

**Comment by jakobtroidl** [comment]
Yes, I was referring to the Janelia hemibrain dataset. Thanks for the information. I'll wait until they become available.
