### ISSUE TITLE
Mapping TreeNeuron presynapses to postsynaptic bodyID

### ISSUE THREAD

**Issue by jakobtroidl** [navis-org/navis#84]
A TreeNeuron object contains an attribute _presynapses_.  The _presynapse_ dataframe gives me information about the connector_id, the node_id etc..., but I am not sure what's the most reliable way to map a from a TreeNeuron presynapse dataframe to the postsynaptic body ID. What's the best way to do this? I am working with the neuprint interface on the hemibrain dataset v1.2.1.

**Comment by schlegelp** [comment]
OK, first some background:
1. `neuron.presynapses` is just a shorthand for `neuron.connectors[neuron.connectors.type == 'pre']`
2. For the neuprint interface these connector tables are collected via [`neuprint.fetch_synapses`](https://github.com/connectome-neuprint/neuprint-python/blob/5e10ebfd4cdd3bb8ef5e4ec40aeca2764ec9621f/neuprint/queries/synapses.py#L17) 
3. The `id` column `neuron.connectors` for neuPrint neurons is simply the index - i.e. has no correspondence in in neuPrint

The function that gives you both x/y/z coordinates and pre- and postsynaptic IDs is `neuprint.fetch_synapse_connections`:

```python
>>> import navis.interfaces.neuprint as neu 
>>> client = neu.Client("https://neuprint.janelia.org", dataset="hemibrain:v1.2.1")
>>> syn = neu.fetch_synapse_connections(neu.NeuronCriteria(bodyId=722817260)
>>> syn.head()
   bodyId_pre  bodyId_post roi_pre roi_post  x_pre  y_pre  z_pre  x_post  y_post  z_post  confidence_pre  confidence_post
0   722817260    884446447   LH(R)    LH(R)   5573  22364  16876    5581   22377   16889           0.978         0.968289
1   722817260   1043117106  SCL(R)   SCL(R)   9888  18000  12487    9907   18004   12496           0.987         0.996399
2   722817260   1043117106  SCL(R)   SCL(R)   9962  17998  12445    9947   18014   12454           0.989         0.924955
3   722817260   1041594248   LH(R)    LH(R)   4757  22909  14635    4782   22895   14644           0.995         0.687169
4   722817260   1857816954   AL(R)    AL(R)  15988  34357  25978   16006   34360   25962           0.904         0.722558
```

With that you have two options:
1. You can use that data to create your own, more detailed `.connectors` table. Note that navis minimally expects `connector_id`, `x`, `y`, `z`, and `type` columns, so you will have to rename some columns and add a "fake" id column.
2. AFAIK, the x/y/z coordinates of synapses serve as their unique identifiers in neuPrint/DVID - i.e. each x/y/z can only ever have a single synapse. You can use that to map rows in `syn` to those in `neuron.connectors` via the `pre_x`/`pre_y`/`pre_z` and `x`/`y`/`z` columns, respectively.

Let me know if you need more pointers.

**Comment by jakobtroidl** [comment]
Thank you for the detailed reply, Philipp. That answers all my questions.
